#!/bin/bash

docker run -it --rm -e PHP_IDE_CONFIG="serverName=PloxHost" -e XDEBUG_SESSION=1 -v $PWD:/app -w /app -u $(id -u):$(id -g) --add-host=host.docker.internal:host-gateway phpdev bash -c "php vendor/bin/pest $@"
