<?php

namespace Lox\Runtime\Types;

class NumberType extends Type
{
    #[\Override] public static function getType(): LoxType
    {
        return LoxType::Number;
    }

    public function __construct(
        public readonly float $value
    )
    {
    }

    #[\Override] public function cast(LoxType $toType): Type
    {
        switch ($toType) {
            case LoxType::Boolean:
                return new BooleanType($this->value !== 0.0);
            case LoxType::Number:
                return $this;
            case LoxType::String:
                return new StringType("$this->value");
        }
        return parent::cast($toType); // TODO: Change the autogenerated stub
    }

}