<?php

namespace Lox\Runtime\Values;

use Lox\Runtime\Errors\InvalidMathError;
use Lox\Scan\Token;
use Lox\Scan\TokenType;

class NilValue extends Value
{
    #[\Override] public static function getType(): ValueType
    {
        return ValueType::NIL;
    }

    public function __construct(
        public readonly null $value = null
    )
    {
    }

    #[\Override] public function cast(ValueType $toType): Value
    {
        switch ($toType) {
            case ValueType::Boolean:
                return new BooleanValue(false);
            case ValueType::String:
                return new StringValue('nil');
        }
        return parent::cast($toType); // TODO: Change the autogenerated stub
    }

    #[\Override] public function compare(Value $value, Token $operatorToken): Value
    {
        switch ($operatorToken->type) {
            case TokenType::EQUAL_EQUAL:
                if ($value::getType() == ValueType::NIL) return new BooleanValue(true);
            case TokenType::BANG_EQUAL:
                if ($value::getType() == ValueType::NIL) return new BooleanValue(false);
            case TokenType::GREATER:
            case TokenType::GREATER_EQUAL:
                return new BooleanValue(true);
            case TokenType::LESS:
            case TokenType::LESS_EQUAL:
                return new BooleanValue(false);
        }

        return parent::compare($value, $operatorToken);
    }

    #[\Override] public function calc(Value $value, Token $operatorToken): Value
    {
        throw new InvalidMathError($operatorToken, "Arithmetic actions with nil are not allowed");
    }


}