<?php

namespace Lox\Runtime\Values;

class NumberValue extends Value
{
    #[\Override] public static function getType(): ValueType
    {
        return ValueType::Number;
    }

    public function __construct(
        public readonly float $value
    )
    {
    }

    #[\Override] public function cast(ValueType $toType): Value
    {
        switch ($toType) {
            case ValueType::Boolean:
                return new BooleanValue($this->value !== 0.0);
            case ValueType::Number:
                return $this;
            case ValueType::String:
                return new StringValue("$this->value");
        }
        return parent::cast($toType); // TODO: Change the autogenerated stub
    }

}