<?php

namespace src\Interpreter\Runtime\Values;

use src\AST\Expressions\Expression;
use src\AST\Statements\Statement;
use src\Interpreter\Runtime\Errors\RuntimeError;
use src\Interpreter\Runtime\ExecutionContext;
use src\Interpreter\Runtime\LoxType;
use src\Interpreter\Runtime\Traits\HasVisibilityAssertion;
use src\Interpreter\Runtime\Util\FieldDefinition;
use src\Resolver\LoxClassPropertyVisibility;
use src\Scaner\Token;
use src\Services\IdService;

class InstanceValue extends BaseValue implements GetAccess, SetAccess
{
    use HasVisibilityAssertion;

    public readonly int $id;

    public function __construct(
        public readonly ClassValue $class,
        private array              $fields = [])
    {
        $this->id = dependency(IdService::class)->createId();
    }

    public function getType(): LoxType
    {
        return LoxType::Instance;
    }

    public function cast(LoxType $toType, Expression|Statement $cause): BaseValue
    {
        if ($toType == LoxType::String) {
// TODO: add reference to file / line?
            $name = $this->class->getName() ?? "anonymous";
            return new StringValue("<instance of {$name}>");
        }

        return parent::cast($toType, $cause); // TODO: Change the autogenerated stub
    }

    public function getOrFail(Token $name, ExecutionContext $executionContext)
    {
        if (isset($this->fields[$name->lexeme])) {
            $property = $this->fields[$name->lexeme];
            $this->assertVisibilityAccess($property, $executionContext, $name, $this->class);
            return $this->fields[$name->lexeme]->value;
        }


        $method = $this->class->getMethod($name->lexeme);
        if ($method !== null) {
            $this->assertVisibilityAccess($method, $executionContext, $name, $this->class);
            return $method->bindInstance($this);
        }

        throw  new RuntimeError($name, "Undefined propery '$name->lexeme'");
    }

    public function setOrFail(Token $name, Value $value, ExecutionContext $executionContext): Value
    {
        if ($this->hasMethod($name)) {
            throw new RuntimeError($name, "Can't overwrite methods.");
        }

        if (!isset($this->fields[$name->lexeme])) {
            $this->fields[$name->lexeme] = new FieldDefinition(LoxClassPropertyVisibility::PUBLIC, $value);
            return $value;
        } else {
            $this->assertVisibilityAccess($this->fields[$name->lexeme], $executionContext, $name, $this->class);
            return $this->fields[$name->lexeme]->value = $value;
        }
    }

    private function hasMethod(Token $name): bool
    {
        return $this->class->getMethod($name->lexeme) !== null;
    }

}