<?php

namespace src\Interpreter\Runtime\Values;

use src\AST\Expressions\Expression;
use src\AST\Statements\Statement;
use src\Interpreter\Runtime\Errors\RuntimeError;
use src\Interpreter\Runtime\LoxType;
use src\Scaner\Token;

class InstanceValue extends BaseValue implements GetAccess, SetAccess
{

    public function __construct(
        public readonly ClassValue $class,
        private array              $fields = [])
    {
    }

    public function getType(): LoxType
    {
        return LoxType::Instance;
    }

    public function cast(LoxType $toType, Expression|Statement $cause): BaseValue
    {
        if ($toType == LoxType::String) {
// TODO: add reference to file / line?
            $name = $this->class->getName() ?? "anonymous";
            return new StringValue("<instance of {$name}>");
        }

        return parent::cast($toType, $cause); // TODO: Change the autogenerated stub
    }


    public function get(Token $name)
    {
        if (isset($this->fields[$name->lexeme])) {
            return $this->fields[$name->lexeme]->value;
        }

        $method = $this->class->getMethod($name->lexeme);
        if ($method !== null) {
            return $method->bindInstance($this);
        }

        throw new RuntimeError($name, "Undefined propery '$name->lexeme'");
    }

    public function set(Token $name, Value $value): Value
    {
        return $this->fields[$name->lexeme]->value = $value;
    }
}