<?php

namespace Lox\Runtime\Native\Functions;

use Lox\AST\Expressions\Expression;
use Lox\AST\Statements\Statement;
use Lox\Runtime\LoxType;
use Lox\Runtime\Values\BaseValue;
use Lox\Runtime\Values\CallableValue;
use Lox\Runtime\Values\StringValue;

abstract class NativeFunction extends BaseValue implements CallableValue
{
    public function getType(): LoxType
    {
        return LoxType::Callable;
    }


    #[\Override] public function cast(LoxType $toType, Statement|Expression $cause): BaseValue
    {
        if ($toType == LoxType::String) {
            return new StringValue("<native fn>");
        }
        return parent::cast($toType, $cause); // TODO: Change the autogenerated stub
    }


}